### ISSUE TITLE
Create incident report data definition

### ISSUE THREAD

**Issue by hannahleland** [mboufal/IPRO-Commuter-Safety#29]
- [x] determine what elements are crucial for incident reporting 
- [x] determine type of data related to the elements
- [x] apply the findings in the database design

**Comment by mboufal** [comment]
[Schema Design.docx](https://github.com/mboufal/IPRO-Commuter-Safety/files/8028943/Schema.Design.docx)

**Comment by mboufal** [comment]
https://github.com/mboufal/IPRO-Commuter-Safety/blob/main/schema_design.md

Directory to the document in the Repository

**Comment by mboufal** [comment]
https://github.com/mboufal/IPRO-Commuter-Safety/blob/main/DB-crime_types.md

Directory to the file with information about the crime. The database table can be found under the schema_design file
